image: $CI_REGISTRY/e3n/devops/docker-image-php:8.2-10

include:
    -   project: 'e3n/symfony/symfony-ci'
        file: '/template.yaml'

stages:
    - setup
    - static_code_analysis
    - security
    - test
    - build

variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: db
    MYSQL_PASSWORD: db
    MYSQL_DATABASE: db_test

.phpunit_template:
    services:
        -   name: mysql:8.0
            alias: db
