#!/bin/bash

## Description: Clear doctrine caches collection-region, entity-region, metadata, query, query-region and result
## Usage: doctrine-clear-caches
## Example: "ddev doctrine-clear-caches"

console doctrine:cache:clear-collection-region
console doctrine:cache:clear-entity-region
console doctrine:cache:clear-metadata
console doctrine:cache:clear-query
console doctrine:cache:clear-query-region
console doctrine:cache:clear-result
